### ISSUE TITLE
WSL2不支持挂载Minix镜像

### ISSUE THREAD

**Issue by ZhengQinLai** [CN-GuoZiyang/oslab-oneclick#2]
内核好像被动过...总之实验 “系统调用” 中挂载会失败：
lai@LZQ:~/oslab$ sudo ./mount-hdc
mount: /home/lai/oslab/hdc: unknown filesystem type 'minix'.

所以还是不建议使用wsl2

**Comment by CN-GuoZiyang** [comment]
之前遇到过这个问题，写了一篇关于编译自己的 WSL 内核的教程可以看看，可以解决这个问题
https://blog.csdn.net/qq_40856284/article/details/106535962

**Comment by ZhengQinLai** [comment]
LGTM, thx
: )

**Comment by CN-GuoZiyang** [comment]
reopen if not work
